CREATE TABLE TB_RESERVATION (
    id UUID PRIMARY KEY,
    startAt TIMESTAMP NOT NULL,
    endAt TIMESTAMP NOT NULL,
    idRoom UUID NOT NULL,
    idUser UUID NOT NULL,
    FOREIGN KEY (idRoom) REFERENCES TB_ROOMS(id),
    FOREIGN KEY (idUser) REFERENCES TB_USERS(id)
);
